import { DataDen } from './src/data-den';
import { DataDenOptions } from './src/data-den-options.interface';
import { DataDenDefaultCellRenderer } from './src/modules/rendering/cell/data-den-default-cell-renderer';
const options: DataDenOptions = {
  mode: 'client',
  columns: [
    {
      field: 'car',
      headerName: 'Car',
      sort: true,
      filter: false,
      filterOptions: {
        method: 'includes',
        debounceTime: 500,
        caseSensitive: false,
      },
      resize: true,
      width: 100,
      cellRenderer: new DataDenDefaultCellRenderer({ value: 'test' }),
    },
    {
      field: 'model',
      headerName: 'Model',
      sort: true,
      filter: false,
      filterOptions: {
        method: 'includes',
        debounceTime: 500,
        caseSensitive: false,
      },
      resize: true,
      width: 120,
      cellRenderer: new DataDenDefaultCellRenderer({ value: 'test' }),
    },
    {
      field: 'year',
      headerName: 'Year',
      sort: true,
      filter: false,
      filterOptions: {
        method: 'includes',
        debounceTime: 500,
        caseSensitive: false,
      },
      resize: true,
      width: 80,
      cellRenderer: new DataDenDefaultCellRenderer({ value: 'test' }),
    },
    {
      field: 'price',
      headerName: 'Price',
      sort: true,
      filter: false,
      filterOptions: {
        method: 'includes',
        debounceTime: 500,
        caseSensitive: false,
      },
      resize: false,
      width: 60,
      cellRenderer: new DataDenDefaultCellRenderer({ value: 'test' }),
    },
  ],
  rows: [
    { car: 'Honda', model: 'Civic', year: 2013, price: 28000 },
    { car: 'Mitsubishi', model: 'Lancer', year: 2013, price: 56000 },
    { car: 'Porsche', model: 'Boxster', year: 2020, price: 31000 },
    { car: 'Toyota', model: 'Celica', year: 2010, price: 18000 },
    { car: 'Kia', model: 'Sportage', year: 2006, price: 28000 },
    { car: 'Ford', model: 'Focus', year: 2014, price: 24000 },
    { car: 'Ford', model: 'Focus', year: 2010, price: 24000 },
    { car: 'Porsche', model: 'Boxster', year: 2005, price: 31000 },
    { car: 'Mitsubishi', model: 'Lancer', year: 2006, price: 18000 },
    { car: 'Kia', model: 'Sportage', year: 2013, price: 24000 },
    { car: 'Porsche', model: 'Boxster', year: 2004, price: 28000 },
    { car: 'Toyota', model: 'Celica', year: 2004, price: 12000 },
    { car: 'Mitsubishi', model: 'Lancer', year: 2010, price: 34000 },
    { car: 'Toyota', model: 'Celica', year: 2004, price: 18000 },
    { car: 'Lamborghini', model: 'Aventador', year: 2005, price: 56000 },
    { car: 'Nissan', model: 'X-Trail', year: 2013, price: 56000 },
    { car: 'Honda', model: 'Civic', year: 2013, price: 15000 },
    { car: 'Porsche', model: 'Boxster', year: 2005, price: 24000 },
    { car: 'Ford', model: 'Focus', year: 2006, price: 15000 },
    { car: 'Lamborghini', model: 'Aventador', year: 2006, price: 15000 },
    { car: 'Ford', model: 'Focus', year: 2020, price: 12000 },
    { car: 'Honda', model: 'Civic', year: 2005, price: 34000 },
    { car: 'Mitsubishi', model: 'Lancer', year: 2020, price: 34000 },
    { car: 'Honda', model: 'Civic', year: 2020, price: 12000 },
    { car: 'Mitsubishi', model: 'Lancer', year: 2020, price: 15000 },
    { car: 'Ford', model: 'Focus', year: 2004, price: 24000 },
    { car: 'Nissan', model: 'X-Trail', year: 2010, price: 15000 },
    { car: 'Toyota', model: 'Celica', year: 2021, price: 15000 },
    { car: 'Toyota', model: 'Celica', year: 2020, price: 12000 },
    { car: 'Mitsubishi', model: 'Lancer', year: 2020, price: 34000 },
  ],
  pagination: false,
  paginationOptions: {
    pageSize: 10,
  },
  quickFilter: true,
  quickFilterOptions: {
    debounceTime: 500,
  },
};
const ddEl = document.getElementById('dd');
new DataDen(ddEl as HTMLElement, options);
