baseURL = "https://data-den.com/"
languageCode = "en-us"
title = "Data Den"
theme = "ga-hugo-theme"
enableInlineShortcodes = "true"

[params]
apiUrl = "https://getdataden.com/api/docs"
stripePublicKey = "pk_live_GWR9mWvess9zYZONfgf33YQC00lCa4JiRF"
