baseURL = "https://data-den.com/"
languageCode = "en-us"
title = "Data Den"
theme = "ga-hugo-theme"
enableInlineShortcodes = "true"

[params]
apiUrl = "http://localhost:3030"
stripePublicKey = "pk_test_BbH2R0Osif0rDXChYTgUfWhy00enpAgTGb"
